what's new: utilize redirect for BE to read note  json file
tensorflow/tensorboard pull request #4899
Opened 2021-04-21 22:33 UTC by japie1235813

* Motivation for features / changes
We want to read the note content in BE. The design is to bundle the note json file with webfile. Thus we have /notifications_note.json to redirect to.

* Technical description of changes
  - return .json if notifications_note.json present.
  - If the file is absent, the return is 404, error of which is caught in notification_center component (_data_source/ to be specific)
  - for OSS and .dev, this endpoint should never be called

2021-04-22 20:50 UTC, nfelt requested changes

2021-04-23 16:20 UTC, japie1235813 commented on tensorboard/plugins/core/core_plugin.py
> +        return utils.redirect("notifications_note.json")
Addressed

2021-04-23 16:20 UTC, japie1235813 commented on tensorboard/plugins/core/core_plugin_test.py
> +        redirect_link = '<a href="notifications_note.json">'
Modified. Thanks!

2021-04-23 17:44 UTC, nfelt approved these changes

2021-04-23 18:29 UTC, merged