TensorBoard 2.13.0
tensorflow/tensorboard pull request #6370
Opened 2023-05-04 23:26 UTC by rileyajones

Merging the RELEASE notes and version bump into master

2023-05-04 23:40 UTC, arcra requested changes
How about we also cherry-pick the proto changes?

I can also see 3 commits in this PR, but only two files are changed. I believe one commit changed the code from the other one that was cherry-picked?

In general, this step has a similar expectation that it would be "rebased and merged", so we'd want a clean commit history here, and I don't think we ever include the "Tensorboard x.x.x" commit in master. See example in #6193

2023-05-04 23:54 UTC, arcra approved these changes

2023-05-05 01:10 UTC, merged

2023-05-05 08:56 UTC, Corwinpro commented
Hi @rileyajones thank you very much for the release! Just to confirm that a fix to `rustboard` #6251 has been released as well? (sorry did not see that in the change log but it seems that it is in). Thank you!

2023-05-05 16:04 UTC, rileyajones commented
@Corwinpro it is in 12.3.9, I missed adding that to the release notes