2.14.1
tensorflow/tensorboard pull request #6604
Opened 2023-09-27 23:45 UTC by JamesHollyer

Patch release to fix issue #6595

2023-09-28 00:00 UTC, arcra requested changes

2023-10-04 16:50 UTC, groszewn approved these changes

2023-10-06 18:26 UTC, JamesHollyer commented on RELEASE.md
> +# Release 2.12.3# Release 2.10.1
Fixed.

2023-10-06 18:34 UTC, closed without merging

2023-10-06 18:34 UTC, JamesHollyer commented
Closing due to "This branch cannot be rebased due to too many changes" error.